#端口号配置
server:
  port: 8080
#数据库配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/CCDatabase?useSSL=FALSE&serverTimezone=GMT%2B8&characterEncoding=UTF8
    username: root
    password: 123456

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#单个文件最大10MB
  servlet:
    multipart:
      max-file-size: 10MB
#开发环境热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java







